# Generated by Django 2.2.16 on 2023-01-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230122_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(default='60a51281-a346-48b5-9427-bbe5554de59d', editable=False, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
