# Generated by Django 2.2.16 on 2023-01-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230122_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(default='f200f0d8-e3ed-4f1b-b386-7ecb7c469f1c', editable=False, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
