# Generated by Django 2.2.16 on 2023-01-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230114_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(default='104860ab-1128-4736-8c2e-80ca0159b32f', editable=False, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
