# Generated by Django 2.2.16 on 2023-01-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20230114_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
