# Generated by Django 2.2.16 on 2023-01-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(default='6df597bf-00f0-4d49-9c0d-83737e17f52b', editable=False, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
