# Generated by Django 2.2.16 on 2023-01-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230122_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(default='f1e106f6-6970-47f7-a3af-39a6ec6c151b', editable=False, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
