# Generated by Django 2.2.16 on 2023-01-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230114_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(default='af6eb514-114f-430c-b353-bba9429a176a', editable=False, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
