# Generated by Django 2.2.16 on 2023-01-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230114_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(default='a678ae24-8e29-4a35-94b6-3e02c66763b6', editable=False, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
